services:
  tor_privoxy_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # App port
      - "8118:8118" # Privoxy port
    volumes:
      - ./:/app
    environment:
      - TZ=UTC # Set timezone if needed
    restart: unless-stopped

volumes:
  app_data:
